apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
  labels: 
    first: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flower-app
  template: 
    metadata:
      labels:
        app: flower-app
    spec:
      containers:
        - name: flower-app-deployment
          image: nginx:perl
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 81            # service port on which port number you want expose an application
      targetPort: 80      # pod/container port number
  type: NodePort  
  

