apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels: 
    first: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: buntu
  template: 
    metadata:
      labels:
        app: buntu
    spec:
      containers:
        - name: ubuntu-cont
          image: ubuntu:resolute-20260106.1
          ports:
            - containerPort: 80